name: ublue
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
        # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
    # - micro
#     - starship
#     - alacritty
     - qemu-guest-agent
    remove:
    # example: removing firefox (in favor of the flatpak)
    # "firefox" is the main package, "firefox-langpacks" is a dependency
    # - firefox
    # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.google.Chrome
        - org.gnome.Boxes
      # - org.mozilla.firefox
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://downloads.1password.com/linux/flatpak/1Password.flatpakref
      repo-name: onepassword
      repo-title: "1Password (system-wide)"
      install:
        - com.onepassword.OnePassword
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
