name: ublue
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
        # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
#      - https://raw.githubusercontent.com/kristiandrucker/ublue/main/repos/1password.repo
    install:
      - btop
      - zsh
      - doas
      - gtk3-devel
    remove:

  - type: script
    snippets:
      - "rm -f /usr/bin/sudo"
      - "ln -s /usr/bin/doas /usr/bin/sudo"

  - type: gnome-extensions
    install:
      - 'Dash to Dock'
      - 'Blur my Shell'
      - 'Caffeine'
      - 'User Themes'
      - 'Tray Icons: Reloaded'
      - 'Tiling Assistant'

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.Thunderbird
        - com.google.Chrome
        - org.gnome.Boxes
        - com.bitwarden.desktop
        - org.gnome.World.PikaBackup
        - com.mattjakeman.ExtensionManager
      remove:
  
  - type: script
    scripts:
      - catppuccin.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
